import type {
  CommercialInfo,
  ProjectInput,
  StructuralSettings,
} from "./types";
import { DEFAULT_ROOF_RAL, DEFAULT_WALL_RAL } from "./ral";
import { DEFAULT_REGION_ID } from "./regions";
export const defaultStructural: StructuralSettings = {
  regionId: DEFAULT_REGION_ID,
  columnStep: 6000,
  soilId: "auto",
  foundationDepth: 1500,
};
export const defaultCommercial: CommercialInfo = {
  objectName: "",
  objectAddress: "",
  customer: "",
  contact: "",
  managerName: "Муратбеков Эркин",
  managerPhone: "+996 755 405 666",
  factoryName: "Завод БИАСТ",
  factoryAddress:
    "Кыргызстан, г. Бишкек, с. Лебединовка, проспект Ленина, 312",
};
export const defaultProject: ProjectInput = {
  building: { length: 12000, width: 8000, wallHeight: 4000 },
  roof: {
    type: "gable",
    inputMode: "height",
    ridgeHeight: 6000,
    highSideHeight: 6000,
    slopeAngle: 26.565,
    slopeDirection: "left-to-right",
    eaveOverhang: 300,
    gableOverhang: 300,
  },
  wallPanelSystem: {
    thickness: 100,
    ralColor: DEFAULT_WALL_RAL,
    insulation: "basalt",
    effectiveWidth: 1000,
    nominalWidth: 1000,
    maxLength: 12000,
    layoutDirection: "horizontal",
    alignment: "center",
    manualOffset: 0,
    minimumEdgeWidth: 300,
  },
  roofPanelSystem: {
    thickness: 100,
    ralColor: DEFAULT_ROOF_RAL,
    insulation: "basalt",
    effectiveWidth: 1000,
    nominalWidth: 1000,
    maxLength: 12000,
    overlapLength: 200,
    layoutDirection: "vertical",
    alignment: "center",
    manualOffset: 0,
    minimumEdgeWidth: 300,
  },
  openings: [],
  calculationSettings: {
    reservePercent: 5,
    pricingMode: "blank-area",
    subtractOpenings: true,
    showWaste: true,
    groupPanels: true,
    groupMirrored: false,
    rounding: 1,
    wallPricePerM2: 1800,
    roofPricePerM2: 2000,
    ridgePricePerM: 450,
    cornerPricePerM: 450,
    basePricePerM: 450,
    eavePricePerM: 450,
    gablePricePerM: 450,
    fastenerPrice: 9,
    fastenersPerM2: 5,
    flashingReservePercent: 5,
    flashingOverlap: 100,
    mountPanelPricePerM2: 600,
    mountFlashingPricePerM: 150,
    productivityPerDay: 80,
    transportDistanceKm: 20,
    transportRatePerKm: 120,
  },
  commercial: defaultCommercial,
  structural: defaultStructural,
};
